# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='m_mail',
            field=models.EmailField(default=0, max_length=70),
            preserve_default=False,
        ),
    ]
